### ISSUE TITLE
TypeError: DBAPITypeObject(['INT', 'INTEGER', 'SMALLINT']) is not JSON serializable

### ISSUE THREAD

**Issue by HenryBeWell** [ibmdb/python-ibmdbsa#101]
env:
- python 2.7.5
- django 1.11.29
- os centos7
- ibm-db 3.0.4
- ibm-db-sa 0.3.6
- sqlalchemy 1.3.17

traceback
```python
Traceback (most recent call last):
  File "/opt/software/mytemp/hue-release-4.9.0/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/opt/software/mytemp/hue-release-4.9.0/desktop/libs/notebook/src/notebook/api.py", line 235, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/opt/software/mytemp/hue-release-4.9.0/desktop/libs/notebook/src/notebook/api.py", line 196, in _execute_notebook
    history.update_data(notebook)
  File "/opt/software/mytemp/hue-release-4.9.0/desktop/core/src/desktop/models.py", line 1245, in update_data
    self.data = json.dumps(data_dict)
  File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: DBAPITypeObject(['INT', 'INTEGER', 'SMALLINT']) is not JSON serializable
```
query : `SELECT * FROM catalog`
engine is `"db2+ibm_db://user:pwd@host:port/db"`
any help? thanks！

**Comment by amukherjee28** [comment]
Can we please provide an example through sample code, so that we can understand a bit more on what exactly you are trying here.

**Comment by HenryBeWell** [comment]
hi@amukherjee28 , first of all ,thank you for your reply.
question is I want to integrate db2 into hue
ini 
```
[[[db2]]]
    name = DB2
    interface=sqlalchemy
    options='{"url": "db2+ibm_db://user:pwd@host:port/db"}'
```
![image](https://user-images.githubusercontent.com/37875524/122027135-6d5a8180-cdfd-11eb-9fc0-11d9ac78f129.png)

**Comment by amukherjee28** [comment]
Hi @HenryBeWell 

Thank you providing some insight on this.

If I understand correctly, you are trying to connect to a DB2 database through hue using the sqlalchemy driver.

I will check on this and come back with more details on the support.

Thanks.

**Comment by bchoudhary6415** [comment]
Hello @HenryBeWell
Please use latest version of ibm_db, ibm_db_sa and python and verify the issue.
Thank you

**Comment by bchoudhary6415** [comment]
Since No response from the user, I'm closing the issue.
If the user encounters any further errors, they are welcome to reopen the issue.
