### ISSUE TITLE
DB2 on AS400: An unexpected token "ISOLATION" was found on ibm_db_sa/ibm_db.py

### ISSUE THREAD

**Issue by SSRico** [ibmdb/python-ibmdbsa#40]
**[Environment]**
Database Server: DB2 on AS400 with DB2 Connect installed to allow TCP/IP connections (connection tested using ibm_db and the default port number)
Application Server: Linux server running Python 3 + Flask application, using ibm_db, ibm_db_sa and SQLAlchemy.

**[Problem]**
Trying to run a simple query to test that the connection from the application server to the test server is working when using SQLAlchemy + ibm_db_sa adapter:

```
# Tried using two different adapter names
engine = sqlalchemy.create_engine('ibm_db_sa://user:secret@database_server.host.com:446/database1')
engine = sqlalchemy.create_engine("db2+ibm_db://user:secret@database_server.host.com:446/database1')
result = engine.execute("select USER from USERS")
for row in result:
    print("USER:", row['USER'])
```

This produces the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_dbi.py", line 1235, in _set_cursor_helper
    num_columns = ibm_db.num_fields(self.stmt_handler)
Exception: SQLNumResultCols failed: [IBM][CLI Driver][AS] SQL0104N  An unexpected token "ISOLATION" was found following "".  Expected tokens may include:  "SERVER CLIENT_ACCTNG CLIENT_APPLNAME CLIENT_PROGRAMID CLIE".  SQLSTATE=42601 SQLCODE=-104

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 684, in __connect
    exec_once(self.connection, self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 274, in exec_once
    self(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 1334, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 183, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/base.py", line 695, in initialize
    super(DB2Dialect, self).initialize(connection)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 274, in initialize
    self.get_isolation_level(connection.connection)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/ibm_db.py", line 135, in get_isolation_level
    cursor.execute('SELECT CURRENT ISOLATION FROM sysibm.sysdummy1')
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_dbi.py", line 1355, in execute
    self._set_cursor_helper()
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_dbi.py", line 1238, in _set_cursor_helper
    raise self.messages[len(self.messages) - 1]
ibm_db_dbi.ProgrammingError: ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][AS] SQL0104N  An unexpected token "ISOLATION" was found following "".  Expected tokens may include:  "SERVER CLIENT_ACCTNG CLIENT_APPLNAME CLIENT_PROGRAMID CLIE".  SQLSTATE=42601 SQLCODE=-104

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_sqla.py", line 12, in <module>
    result = engine.execute("select USER from USERS")
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2074, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 684, in __connect
    exec_once(self.connection, self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 274, in exec_once
    self(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 1334, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 183, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/base.py", line 695, in initialize
    super(DB2Dialect, self).initialize(connection)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 274, in initialize
    self.get_isolation_level(connection.connection)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/ibm_db.py", line 135, in get_isolation_level
    cursor.execute('SELECT CURRENT ISOLATION FROM sysibm.sysdummy1')
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_dbi.py", line 1355, in execute
    self._set_cursor_helper()
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_dbi.py", line 1238, in _set_cursor_helper
    raise self.messages[len(self.messages) - 1]
sqlalchemy.exc.ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][AS] SQL0104N  An unexpected token "ISOLATION" was found following "".  Expected tokens may include:  "SERVER CLIENT_ACCTNG CLIENT_APPLNAME CLIENT_PROGRAMID CLIE".  SQLSTATE=42601 SQLCODE=-104 (Background on this error at: http://sqlalche.me/e/f405)
```
I also tried using table models instead of using my own query, tried using Python 2.7 as well. Everything returned the same error code
```
sqlalchemy.exc.ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: 
SQLNumResultCols failed: [IBM][CLI Driver][AS] SQL0104N  An unexpected token "ISOLATION" was found following "".  
Expected tokens may include:  "SERVER CLIENT_ACCTNG CLIENT_APPLNAME CLIENT_PROGRAMID CLIE".  
SQLSTATE=42601 SQLCODE=-104 (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by abhi7436** [comment]
Hi,
Can you please use adapter like below
engine = sqlalchemy.create_engine('ibm_db_sa+**pyodbc400**://user:secret@database_server.host.com:446/database1')

this should resolve your issue.
Let us know if issue still persist.

Thanks,
Abhinav

**Comment by SSRico** [comment]
Hi @abhi7436 , 
Thanks for your quick response, I tested it on Python 3 without luck, it seems that pyodbc is not fully supporting the new syntax on Python 3.
```
File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/__init__.py", line 424, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 92, in create
    (cargs, cparams) = dialect.create_connect_args(u)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/pyodbc.py", line 147, in create_connect_args
    connectors.extend(['%s=%s' % (k,v) for k,v in keys.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'
```

I'll try it on a different environment using Python 2.7 to verify if the suggested adapter fixes the problem.

**Comment by SSRico** [comment]
I am still testing it on Python 3, I made some code changes on the pyodbc.py file to support the iteritems function, after that I was able to connect to the database.
The following are the extra steps I had to do in order to set the connection:
1. I had to configure an ODBC connection on my Linux environment.
2. The driver name of the ODBC connection must be "iSeries Access ODBC Driver"

After a successful connection I tried running a query 
```
result = engine.execute("select USER from USERS")
for row in result:
    print("USER:", row['USER'])
```
The following is the error I got:
```
Traceback (most recent call last):
  File "test_sqla.py", line 12, in <module>
    result = engine.execute("select USER from USERS")
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2074, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 684, in __connect
    exec_once(self.connection, self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 274, in exec_once
    self(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 1334, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 183, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/base.py", line 695, in initialize
    super(DB2Dialect, self).initialize(connection)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 268, in initialize
    self._get_default_schema_name(connection)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/base.py", line 706, in _get_default_schema_name
    return self._reflector._get_default_schema_name(connection)
  File "/usr/local/lib/python3.5/dist-packages/ibm_db_sa/reflection.py", line 69, in _get_default_schema_name
    u'SELECT CURRENT_SCHEMA FROM SYSIBM.SYSDUMMY1').scalar()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)

TypeError: The first argument to execute must be a string or unicode query.
```

Any thoughts about the issue?

**Comment by SSRico** [comment]
Hi @abhi7436 
In the following  [commit](https://github.com/SSRico/python-ibmdbsa/commit/660a0e4e13532b6e2465f45d0e06ed6cb9d6ca60) under my own repository, I added some fixes that allowed me to run the select query I was trying to run. I haven't tested using models or any other CRUD action yet, but it's a progress, please check the fixes and let me know your thoughts.

Thanks
- Samir Silva

**Comment by abhi7436** [comment]
Hi @SSRico ,
I saw your code changes and it is very much similar to the changes what I have made. 
I am in process of testing and reviewing it. Will push code shortly in repository.

Thank you for sharing the code.

Thanks,
Abhinav

**Comment by abhi7436** [comment]
Fix merged in Git. Will close this issue.

**Comment by SSRico** [comment]
Hi @abhi7436 ,
I downloaded the updated source code and installed it using $python3 setyp.py install and verified the issue is not occurring anymore, Thanks a lot for your help.
Quick question: This updated module is not available on pypi.org, is it? When is it going to be available?

Best regards

- Samir Silva
