### ISSUE TITLE
ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdbsa#46]
```
Traceback (most recent call last):
File "alchemy_test.py", line 3, in <module>
import ibm_db_sa.ibm_db_sa
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/init.py", line 22, in <module>
from . import ibm_db, pyodbc, base, zxjdbc
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/ibm_db.py", line 20, in <module>
from .base import DB2ExecutionContext, DB2Dialect
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/base.py", line 30, in <module>
from . import reflection as ibm_reflection
File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_sa/reflection.py", line 26, in <module>
from future.utils import iteritems
ModuleNotFoundError: No module named 'future'
```

Looks like 
https://github.com/ibmdb/python-ibmdbsa/pull/43/commits/a5bb019d434c54b08cdef079c4624715c296e05c#diff-b3a9e1dd4976b655040c5eebb69309d1L24 added a dependency on the future package, but it wasn't added as a dependency to setup.py.

**Comment by congmingdexiong** [comment]
Same error, awaiting for the fix

**Comment by gokycat** [comment]
also waiting

**Comment by thecyman** [comment]
FYI, I used `pip3 install ibm_db` and it still gave this error.. My guess is this hasn't been rolled out entirely yet.

**Comment by abhishekbatra** [comment]
This issue still seems to be present with the same same guilty code that was supposed to have been removed in the above quoted fix.

>     from . import reflection as ibm_reflection
  File "virtualenv/lib/python3.6/site-packages/ibm_db_sa/reflection.py", line 26, in <module>
    from future.utils import iteritems
ModuleNotFoundError: No module named 'future'

**Comment by PeterFogh** [comment]
Please fix the `No module named 'future'` bug in version 0.3.4, by releasing [220029f](https://github.com/ibmdb/python-ibmdbsa/commit/220029fd7455c62b69dadd3c3d60744c11b76ccb) as a new version.
