### ISSUE TITLE
Add support isolation levels

### ISSUE THREAD

**Issue by annasort** [ibmdb/python-ibmdbsa#5]
ibm_db_sa does not support isolation levels. When DB2 is used as ceilometer backend, this lack of support of isolation levels causes failures in REST API /v2/events:

2015-09-14 10:51:05.879 542 ERROR wsme.api [req-32584490-e803-4851-87fa-84ccb99595d8 - - - - -] Server-side error: "". Detail: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/wsmeext/pecan.py", line 84, in callfunction
    result = f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/ceilometer/api/controllers/v2/events.py", line 258, in get_all
    limit)]
  File "/usr/lib/python2.7/site-packages/ceilometer/event/storage/impl_sqlalchemy.py", line 220, in get_events
    execution_options={'isolation_level': self.isolation_level})
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 882, in connection
    execution_options=execution_options)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 887, in _connection_for_bind
    engine, execution_options)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 337, in _connection_for_bind
    conn = conn.execution_options(**execution_options)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 285, in execution_options
    self.dialect.set_connection_execution_options(c, opt)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 403, in set_connection_execution_options
    self._set_connection_isolation(connection, opts['isolation_level'])
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 412, in _set_connection_isolation
    self.set_isolation_level(connection.connection, level)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/interfaces.py", line 716, in set_isolation_level
    raise NotImplementedError()

ibm_db_sa should support isolation levels similar to other db's.

**Comment by hemlatabhatt** [comment]
Support is present in ibm_db_sa .

**Comment by leucir** [comment]
@hemlatabhatt this is not currently supported when using create_engine.
Passing `isolation_level` as a parameter to create_engine generates a `TypeError` exception, once that parameter is not being expected by the driver. 
Can you post here what is the correct way to set the `isolation_level`, please?
